### ISSUE TITLE
example for classifying time series data

### ISSUE THREAD

**Issue by vinayakumarr** [Benli11/DMDpack#1]
I have data which has 50000 rows. In that 41 features and 23classes. Is it possible to apply dynamic mode decomposition. If so can you give an example for classifying my dataset

**Comment by erichson** [comment]
If I get you right, you have a data matrix **A** of size 50000x41, while the 41 features are ordered and evolving over time? 

Using the DMD you can try for starters something as follows: 

```
import numpy as np
from dmd import dmd
DMD_modes, amplitudes , V, omega = dmd(A, dt=1, return_vandermonde=True, return_amplitudes=True)

```

Once you have obtained the DMD modes and amplitudes, you can create _k_ new features, e.g., _k=10_ as

```
k=10
new_features = np.dot(DMD_modes[:,0:k], np.diag(amplitudes[0:k]))
```

You can use the _new_features_ then as input for your learning algorithm (most likely you are just interested in the real part, i.e., `new_features = new_features.real`. 

Note, that the DMD_modes are here returned sorted so that the first mode is corresponding to the most stable mode, etc. You might want to select features which are more relevant for you specific applications (_k=10_ was here just an arbitrary choice). You can get some good insights by plotting omega:

```
from dmd import tools
tools.plot_modes(omega)
```

Let me know how this goes. 

Cheers,
B

**Comment by vinayakumarr** [comment]
I am trying to model this data as time series data . I am new to this. My question is is it possible to solve this type of problem using DMD. I have finished a course on linear algebra and optimization and i came to know dmd is an extension of SVD. So could you briefly tell us what is DMD and how it can be applied for my problem

What is A in the above given code and also could you give a basic code for modelling this timeseries data for classification

**Comment by vinayakumarr** [comment]
k i understood A is  50000x41 but i have class label also (23 classess) 

example of my dataset

classlabel      features 41

0,               0,0.00018349,0.00018349,0.00018349,....
22              0,0.0039216,0.19608,0.0039216.....    

also where is the code for   "You can use the new_features then as input for your learning algorithm".

**Comment by vinayakumarr** [comment]
I am running a program in server. It generates the following error
![untitled](https://cloud.githubusercontent.com/assets/18217467/16978837/b16ecde2-4e7b-11e6-84f8-52f18692f214.png)

**Comment by erichson** [comment]
Do you just want to visualize your data or is your aim to come up with a classification model, e.g., logistic regression or gradient boosting machine. Indeed DMD can help you to extract some new features (as an alternative for SVD/PCA), however, I am not sure if they are meaningful without knowing the data better. The DMD features can be used for visualization or as input for your learning algorithm.  DMD is an unsupervised method and cannot help you to do the classification itself. 

Just, that we are on the same page, you have one nominal random variable (the first column of your data matrix) indicating a class, i.e., let's denote this variable _y_ which can take any of the following values {0,2,3....,22}. In addition you have 40 features, i.e., x_1, x_2, .... x_40.  Hence, you omit  _y_ and just feed the 40 features into DMD. 

See also the edits above, you are required to pull a new version in order to use the function `plot_modes()`.
